# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: WNI
logo: "/assets/images/Mountain-512.png"
email : heya@wni.app
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-RD0D33XTR1"
    anonymize_ip: false # default

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
# timezone: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/wni_app/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wni-app/website-mm/"
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/channel/UCfZkPuGdNfHwyjzEBREFnsA/"
    - label: "Email"
      icon: "fas fa-envelope-square"
      url: "mailto:heya@wni.app"

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false
      sidebar:
        - title: "Blog"
          text: "[Recent](/blog/)  \n[Archive](/posts/)  \n[Categories](/categories/)  \n[Tags](/tags/)"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
